export const CUTTERS_REQUEST = 'CUTTERS_REQUEST';
export const CUTTERS_SUCCESS = 'CUTTERS_SUCCESS';
export const CUTTERS_FAILURE = 'CUTTERS_FAILURE';

export const GEOMETRIES_REQUEST = 'GEOMETRIES_REQUEST';
export const GEOMETRIES_SUCCESS = 'GEOMETRIES_SUCCESS';
export const GEOMETRIES_FAILURE = 'GEOMETRIES_FAILURE';

export const SET_SEARCH_FAMILIES_FILTERS = 'SET_SEARCH_FAMILIES_FILTERS';
export const RESET_SEARCH_FAMILIES_FILTERS = 'RESET_SEARCH_FAMILIES_FILTERS';

export const SEARCH_FAMILIES_REQUEST = 'SEARCH_FAMILIES_REQUEST';
export const SEARCH_FAMILIES_SUCCESS = 'SEARCH_FAMILIES_SUCCESS';
export const SEARCH_FAMILIES_FAILURE = 'SEARCH_FAMILIES_FAILURE';
