export const SET_API_TOKEN = 'SET_API_TOKEN';
export const SET_API_LOCALE = 'SET_API_LOCALE';

export const SET_SEARCH_FAMILIES_FILTERS = 'SET_SEARCH_FAMILIES_FILTERS';
export const RESET_SEARCH_FAMILIES_FILTERS = 'RESET_SEARCH_FAMILIES_FILTERS';

export const SEARCH_FAMILIES_REQUEST = 'SEARCH_FAMILIES_REQUEST';
export const SEARCH_FAMILIES_SUCCESS = 'SEARCH_FAMILIES_SUCCESS';
export const SEARCH_FAMILIES_FAILURE = 'SEARCH_FAMILIES_FAILURE';

export const SET_SEARCH_FAMILIES_PAGE = 'SET_SEARCH_FAMILIES_PAGE';

export const SEARCH_FAMILIES_UTENSILS_REQUEST = 'SEARCH_FAMILIES_UTENSILS_REQUEST';
export const SEARCH_FAMILIES_UTENSILS_SUCCESS = 'SEARCH_FAMILIES_UTENSILS_SUCCESS';
export const SEARCH_FAMILIES_UTENSILS_FAILURE = 'SEARCH_FAMILIES_UTENSILS_FAILURE';

export const SEARCH_FAMILIES_GEOMETRIES_REQUEST = 'SEARCH_FAMILIES_GEOMETRIES_REQUEST';
export const SEARCH_FAMILIES_GEOMETRIES_SUCCESS = 'SEARCH_FAMILIES_GEOMETRIES_SUCCESS';
export const SEARCH_FAMILIES_GEOMETRIES_FAILURE = 'SEARCH_FAMILIES_GEOMETRIES_FAILURE';

export const SEARCH_FAMILIES_CUTTERS_REQUEST = 'SEARCH_FAMILIES_CUTTERS_REQUEST';
export const SEARCH_FAMILIES_CUTTERS_SUCCESS = 'SEARCH_FAMILIES_CUTTERS_SUCCESS';
export const SEARCH_FAMILIES_CUTTERS_FAILURE = 'SEARCH_FAMILIES_CUTTERS_FAILURE';
